// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO9OGjS2sCI-CIHWR83UKKMJW0NWWz_IE',
    appId: '1:301343223325:web:d8a81f863cea3118f2a0f4',
    messagingSenderId: '301343223325',
    projectId: 'mediscan-ee2e1',
    authDomain: 'mediscan-ee2e1.firebaseapp.com',
    storageBucket: 'mediscan-ee2e1.appspot.com',
    measurementId: 'G-2FCT2R00CN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC40Lnrcln36XBg4D4ffFumW-PLvujuY9E',
    appId: '1:301343223325:android:8bf9c0fe93c7859af2a0f4',
    messagingSenderId: '301343223325',
    projectId: 'mediscan-ee2e1',
    storageBucket: 'mediscan-ee2e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2C3l-eHas5tTYtQieaO5tny0fQ0YucwI',
    appId: '1:301343223325:ios:43df28ed149693c6f2a0f4',
    messagingSenderId: '301343223325',
    projectId: 'mediscan-ee2e1',
    storageBucket: 'mediscan-ee2e1.appspot.com',
    iosBundleId: 'com.example.mediscanphone3',
  );
}
